services:
  - type: web
    name: prodcontrol-backend
    env: java
    plan: free
    buildCommand: ./prodcontrol-backend/mvnw clean package -DskipTests
    startCommand: java -jar prodcontrol-backend/target/prodcontrol-backend-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: JAVA_OPTS
        value: "-Xmx512m"
    healthCheckPath: /actuator/health
